apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ws-proxy
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  ingresses:
    - https://ws-proxy.intern.dev.nav.no
    - https://ws-proxy.dev-fss-pub.nais.io
  strategy:
    type: Recreate
  azure:
    application:
      enabled: true
  liveness:
    path: /
    initialDelay: 1
  readiness:
    path: /
    initialDelay: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 16Mi
  replicas:
    min: 1
    max: 1